// Dữ liệu độc lập với phần hiển thị: thêm hiện vật chỉ cần thêm một object tại đây.
const ARTIFACTS = [
  { id: "chua-keo", gian: "thaibinh", nhom: "tin-nguong", ten: "Gác chuông chùa Keo", moTaNgan: "Một trong những công trình gỗ cổ được gìn giữ nguyên vẹn nhất Việt Nam.", cauChuyen: "Dựng từ thế kỷ 17, kết cấu hoàn toàn bằng mộng gỗ, không dùng đinh sắt. Hội chùa mở mùa thu, tháng Chín âm lịch, có tục bơi trải trên sông.", banCoBiet: "Gác chuông có 3 tầng mái với 84 cửa dàn quạt.", imageUrl: null, mauSac: "#8C4A2F", trangThai: "mo" },
  { id: "tam-duong", gian: "thaibinh", nhom: "tin-nguong", ten: "Khu lăng mộ Tam Đường", moTaNgan: "Nơi phát tích của vương triều Trần trước khi dời đô về Thăng Long.", cauChuyen: "Tam Đường (Hưng Hà) là nơi an táng các vị tiên tổ nhà Trần, gắn với giai đoạn khởi nghiệp của một trong những triều đại lừng lẫy nhất sử Việt.", banCoBiet: "Khu di tích gồm nhiều lăng mộ và đền thờ nằm rải trên một vùng đất bãi ven sông.", imageUrl: null, mauSac: "#61734f", trangThai: "mo" },
  { id: "cheo-khuoc", gian: "thaibinh", nhom: "nghe-thuat", ten: "Chiếu chèo làng Khuốc", moTaNgan: "Một trong những cái nôi của nghệ thuật chèo.", cauChuyen: "Người làng Khuốc gần như ai cũng biết hát vài câu chèo — từ ruộng lúa bước ra sân khấu là chuyện thường ở đây.", banCoBiet: "Làng Khuốc từng được ví là làng chèo vì mật độ người biết hát, biết diễn cao hiếm nơi nào có.", imageUrl: null, mauSac: "#b56b31", trangThai: "mo" },
  { id: "hoi-chua-keo", gian: "thaibinh", nhom: "nghe-thuat", ten: "Trống hội & rước kiệu chùa Keo", moTaNgan: "Không khí lễ hội đặc trưng của vùng châu thổ.", cauChuyen: "Mỗi mùa thu, hội chùa Keo có rước kiệu, trống hội và tục bơi trải trên sông, thu hút đông đảo người dân và du khách.", banCoBiet: "Hội chùa Keo mùa xuân và mùa thu là hai kỳ hội lớn nhất trong năm của vùng.", imageUrl: null, mauSac: "#a94135", trangThai: "mo" },
  { id: "dong-xam", gian: "thaibinh", nhom: "lang-nghe", ten: "Chạm bạc Đồng Xâm", moTaNgan: "Làng nghề chạm bạc hơn sáu trăm năm tuổi.", cauChuyen: "Hoa văn tinh xảo trên bạc ở Đồng Xâm từng theo chân thợ giỏi ra tận kinh thành để làm đồ tiến vua.", banCoBiet: "Nghệ nhân Đồng Xâm từng được vời vào cung để làm đồ trang sức cho triều đình.", imageUrl: null, mauSac: "#75919a", trangThai: "mo" },
  { id: "chieu-hoi", gian: "thaibinh", nhom: "lang-nghe", ten: "Dệt chiếu Hới", moTaNgan: "Nghề dệt chiếu cói truyền thống hơn 400 năm.", cauChuyen: "Chiếu Hới (Tân Lễ, Hưng Hà) nổi tiếng bền, đẹp, từng là mặt hàng được ưa chuộng ở nhiều vùng.", banCoBiet: "Nghề dệt chiếu ở đây được truyền qua nhiều thế hệ trong cùng một làng.", imageUrl: null, mauSac: "#a39252", trangThai: "mo" },
  { id: "banh-cay", gian: "thaibinh", nhom: "am-thuc", ten: "Bánh cáy làng Nguyễn", moTaNgan: "Món bánh đặc sản từng được tiến vua.", cauChuyen: "Bánh cáy làm từ gạo nếp, mứt, lạc, vừng, có màu vàng đặc trưng, thường xuất hiện dịp Tết.", banCoBiet: "Tên gọi cáy xuất phát từ màu vàng giống trứng cáy, không phải làm từ con cáy.", imageUrl: null, mauSac: "#d59b35", trangThai: "mo" },
  { id: "con-vanh", gian: "thaibinh", nhom: "am-thuc", ten: "Cồn Vành", moTaNgan: "Nơi sông Hồng gặp biển, đất vẫn còn đang bồi.", cauChuyen: "Bãi bồi ven biển với rừng ngập mặn và từng đàn chim di trú — ranh giới mềm giữa đất liền và biển cả.", banCoBiet: "Cồn Vành nằm trong khu dự trữ sinh quyển châu thổ sông Hồng được UNESCO công nhận.", imageUrl: null, mauSac: "#367c87", trangThai: "mo" },
  { id: "van-mieu-xich-dang", gian: "hungyen", nhom: "tin-nguong", ten: "Văn Miếu Xích Đằng", moTaNgan: "Văn miếu cấp tỉnh cổ, biểu tượng khoa bảng đất Hưng Yên.", cauChuyen: "Xây dựng từ thời Hậu Lê, thờ Khổng Tử và các bậc khoa bảng địa phương, là một trong số ít văn miếu cấp tỉnh còn lại.", banCoBiet: "Đây là một trong số ít văn miếu cấp tỉnh còn lại ở Việt Nam, bên cạnh Văn Miếu Quốc Tử Giám.", imageUrl: null, mauSac: "#8C4A2F", trangThai: "khoa" },
  { id: "chu-dong-tu", gian: "hungyen", nhom: "tin-nguong", ten: "Đền Chử Đồng Tử (Đa Hòa)", moTaNgan: "Nơi thờ một trong bốn vị thánh bất tử của người Việt.", cauChuyen: "Gắn với thiên tình sử Chử Đồng Tử và công chúa Tiên Dung bên bãi sông Hồng.", banCoBiet: "Chử Đồng Tử là vị thánh duy nhất trong tứ bất tử xuất thân từ một gia đình nghèo khó.", imageUrl: null, mauSac: "#61734f", trangThai: "khoa" },
  { id: "trong-quan", gian: "hungyen", nhom: "nghe-thuat", ten: "Hát trống quân", moTaNgan: "Lối hát đối đáp nam nữ dùng trống dây.", cauChuyen: "Phổ biến ở vùng Dạ Trạch, thường hát trong các dịp hội hè, mùa gặt, nam nữ đối đáp qua lại bằng lời ca ứng tác.", banCoBiet: "Mặt trống được căng bằng dây, gõ bằng que nứa, âm thanh khác hẳn trống da thông thường.", imageUrl: null, mauSac: "#b56b31", trangThai: "khoa" },
  { id: "hoi-da-hoa", gian: "hungyen", nhom: "nghe-thuat", ten: "Lễ hội Đền Đa Hòa", moTaNgan: "Lễ rước lớn tái hiện thiên tình sử Chử Đồng Tử - Tiên Dung.", cauChuyen: "Tổ chức tháng Hai âm lịch, có tục rước nước từ giữa sông Hồng về đền.", banCoBiet: "Lễ hội có tục rước nước từ giữa sông Hồng, tái hiện cảnh gặp gỡ của đôi nhân vật huyền thoại.", imageUrl: null, mauSac: "#a94135", trangThai: "khoa" },
  { id: "huong-cao-thon", gian: "hungyen", nhom: "lang-nghe", ten: "Hương Cao Thôn", moTaNgan: "Làng nghề làm hương truyền thống.", cauChuyen: "Mùi hương Cao Thôn gắn với ký ức Tết của nhiều thế hệ miền Bắc, từng que hương vẫn được se tay trước khi phơi nắng.", banCoBiet: "Nghề hương ở đây đã truyền qua nhiều đời trong làng.", imageUrl: null, mauSac: "#9b5361", trangThai: "khoa" },
  { id: "duc-dong-long-thuong", gian: "hungyen", nhom: "lang-nghe", ten: "Đúc đồng Lộng Thượng", moTaNgan: "Làng nghề đúc đồng lâu đời.", cauChuyen: "Chuyên chế tác chuông, tượng, đồ thờ cung cấp cho đình chùa nhiều nơi.", banCoBiet: "Nhiều quả chuông và pho tượng ở các ngôi chùa miền Bắc được đúc từ bàn tay nghệ nhân Lộng Thượng.", imageUrl: null, mauSac: "#8c7a43", trangThai: "khoa" },
  { id: "nhan-long", gian: "hungyen", nhom: "am-thuc", ten: "Nhãn lồng Hưng Yên", moTaNgan: "Quả nhãn từng được tiến vua.", cauChuyen: "Cùi dày, hạt nhỏ, vị ngọt thanh, chín rộ mỗi độ tháng Tám.", banCoBiet: "Tên gọi nhãn lồng xuất phát từ việc người xưa lấy lồng bọc quả để tránh chim, dơi ăn mất trước khi tiến vua.", imageUrl: null, mauSac: "#cb9c32", trangThai: "khoa" },
  { id: "tuong-ban", gian: "hungyen", nhom: "am-thuc", ten: "Tương Bần", moTaNgan: "Đặc sản lên men từ đậu tương.", cauChuyen: "Ủ trong chum sành ngoài nắng, là gia vị đặc trưng của ẩm thực Bắc Bộ.", banCoBiet: "Tương Bần từng đi vào ca dao dân gian như một đặc sản vùng miền được nhắc đến rộng rãi.", imageUrl: null, mauSac: "#744123", trangThai: "khoa" }
];

const NHOM = [
  { ma: "tin-nguong", ten: "Tín ngưỡng & kiến trúc" },
  { ma: "nghe-thuat", ten: "Nghệ thuật dân gian" },
  { ma: "lang-nghe", ten: "Làng nghề" },
  { ma: "am-thuc", ten: "Ẩm thực & thiên nhiên" }
];

const GIAN = [
  { ma: "thaibinh", ten: "Gian Thái Bình", trangThai: "mo" },
  { ma: "hungyen", ten: "Gian Hưng Yên", trangThai: "khoa" }
];
